-- --------------------------------------------------------
-- mod-azeroth-friend Database Schema
-- Dynamic autonomous bot agency powered by LLM Cognitive Planner
-- --------------------------------------------------------

-- Registered bot companions and configurations
CREATE TABLE IF NOT EXISTS `azeroth_friend_bots` (
    `bot_guid` INT UNSIGNED NOT NULL,
    `bot_name` VARCHAR(64) NOT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `bridge_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `action_mode` ENUM('combat', 'travel', 'idle', 'social') NOT NULL DEFAULT 'travel',
    `mode` ENUM('companion', 'autonomous', 'guard', 'idle') NOT NULL DEFAULT 'companion',
    `master_guid` INT UNSIGNED DEFAULT NULL,
    `master_name` VARCHAR(64) DEFAULT NULL,
    `affinity` INT NOT NULL DEFAULT 0,
    `personality` VARCHAR(255) DEFAULT 'A helpful and courageous adventurer with a touch of dry humor',
    `current_goal` VARCHAR(255) DEFAULT 'Explore and assist my companions',
    `long_term_goal` TEXT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`bot_guid`),
    KEY `idx_enabled` (`enabled`),
    KEY `idx_bridge_enabled` (`enabled`, `bridge_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Real-time lightweight environment and bot status snapshot
CREATE TABLE IF NOT EXISTS `azeroth_friend_state` (
    `bot_guid` INT UNSIGNED NOT NULL,
    `map_id` INT UNSIGNED NOT NULL,
    `zone_id` INT UNSIGNED NOT NULL,
    `area_id` INT UNSIGNED NOT NULL,
    `pos_x` FLOAT NOT NULL,
    `pos_y` FLOAT NOT NULL,
    `pos_z` FLOAT NOT NULL,
    `orientation` FLOAT NOT NULL,
    `level` TINYINT UNSIGNED NOT NULL,
    `health_pct` TINYINT UNSIGNED NOT NULL,
    `power_pct` TINYINT UNSIGNED NOT NULL,
    `in_combat` TINYINT(1) NOT NULL DEFAULT 0,
    `target_guid` INT UNSIGNED DEFAULT NULL,
    `target_name` VARCHAR(128) DEFAULT NULL,
    `environment_json` JSON DEFAULT NULL,
    `last_thought` TEXT DEFAULT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`bot_guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Event queue for triggers dispatched from C++ to the Python bridge
CREATE TABLE IF NOT EXISTS `azeroth_friend_events` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot_guid` INT UNSIGNED NOT NULL,
    `event_type` VARCHAR(32) NOT NULL,
    `priority` TINYINT UNSIGNED NOT NULL DEFAULT 5,
    `source_guid` INT UNSIGNED DEFAULT NULL,
    `source_name` VARCHAR(64) DEFAULT NULL,
    `payload_json` LONGTEXT DEFAULT NULL,
    `dedup_key` VARCHAR(64) NULL DEFAULT NULL,
    `expires_at` TIMESTAMP NULL DEFAULT NULL,
    `status` ENUM('pending', 'processing', 'completed', 'expired', 'skipped', 'superseded', 'ignored_addon') NOT NULL DEFAULT 'pending',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `processed_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_status_priority` (`status`, `priority`, `created_at`),
    KEY `idx_bot` (`bot_guid`, `status`),
    KEY `idx_events_dedup` (`bot_guid`, `dedup_key`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Action queue: Multi-step plans generated by Python and executed by C++
CREATE TABLE IF NOT EXISTS `azeroth_friend_actions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot_guid` INT UNSIGNED NOT NULL,
    `plan_id` VARCHAR(64) NOT NULL,
    `step_index` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `total_steps` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `action_type` VARCHAR(32) NOT NULL,
    `params_json` JSON NOT NULL,
    `thought` TEXT DEFAULT NULL,
    `control_revision` INT UNSIGNED NULL DEFAULT NULL,
    `origin_event_id` BIGINT UNSIGNED NULL DEFAULT NULL,
    `authority` ENUM('autonomous', 'owner_command', 'gm_manual') NOT NULL DEFAULT 'autonomous',
    `origin_source_guid` INT UNSIGNED NULL DEFAULT NULL,
    `dedup_key` VARCHAR(64) NULL DEFAULT NULL,
    `expires_at` TIMESTAMP NULL DEFAULT NULL,
    `status` ENUM('pending', 'in_progress', 'completed', 'failed', 'interrupted') NOT NULL DEFAULT 'pending',
    `failure_reason` VARCHAR(255) DEFAULT NULL,
    `result_json` LONGTEXT DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `started_at` TIMESTAMP NULL DEFAULT NULL,
    `completed_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_bot_pending` (`bot_guid`, `status`, `step_index`),
    KEY `idx_plan` (`plan_id`),
    KEY `idx_actions_active` (`bot_guid`, `status`, `plan_id`, `step_index`),
    KEY `idx_actions_completion` (`status`, `completed_at`),
    KEY `idx_actions_dedup` (`bot_guid`, `dedup_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Executable action catalogue: curated vocabulary plus the live mod-playerbots
-- action/strategy list exported per bot (.af catalog).
CREATE TABLE IF NOT EXISTS `azeroth_friend_action_catalog` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot_guid` INT UNSIGNED NOT NULL DEFAULT 0,
    `action_name` VARCHAR(96) NOT NULL,
    `category` VARCHAR(48) NOT NULL DEFAULT 'general',
    `source` ENUM('curated', 'playerbots', 'strategy', 'command') NOT NULL DEFAULT 'curated',
    `params_schema` VARCHAR(128) DEFAULT NULL,
    `description` VARCHAR(255) DEFAULT NULL,
    `safe` TINYINT(1) NOT NULL DEFAULT 1,
    `api_version` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `params_schema_json` LONGTEXT DEFAULT NULL,
    `result_schema_json` LONGTEXT DEFAULT NULL,
    `binding_kind` VARCHAR(32) NOT NULL DEFAULT 'semantic_adapter',
    `native_binding` VARCHAR(128) DEFAULT NULL,
    `authority` ENUM('autonomous', 'owner_command', 'gm_manual') NOT NULL DEFAULT 'autonomous',
    `preconditions` VARCHAR(255) DEFAULT NULL,
    `completion_policy` VARCHAR(32) NOT NULL DEFAULT 'dispatch_acknowledged',
    `capability_revision` INT UNSIGNED NOT NULL DEFAULT 1,
    `exported_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_catalog_unique` (`bot_guid`, `source`, `action_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Episodic memory system (narrative history & milestones)
CREATE TABLE IF NOT EXISTS `azeroth_friend_memory` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot_guid` INT UNSIGNED NOT NULL,
    `memory_type` VARCHAR(32) NOT NULL,
    `content` TEXT NOT NULL,
    `importance` TINYINT UNSIGNED NOT NULL DEFAULT 5,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_bot_type` (`bot_guid`, `memory_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rolling bridge telemetry counters (single row, id = 1) read by `.af status`.
CREATE TABLE IF NOT EXISTS `azeroth_friend_telemetry` (
    `id` INT UNSIGNED NOT NULL,
    `co_processed_events` INT UNSIGNED NOT NULL DEFAULT 0,
    `sensory_reused_events` INT UNSIGNED NOT NULL DEFAULT 0,
    `tokens_saved` INT UNSIGNED NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Zero-token structured summaries derived from verified outcomes only.
CREATE TABLE IF NOT EXISTS `azeroth_friend_summaries` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `bot_guid` INT UNSIGNED NOT NULL,
    `goal_identity` VARCHAR(32) NOT NULL DEFAULT '',
    `revision` INT UNSIGNED NOT NULL DEFAULT 0,
    `window_start` TIMESTAMP NULL DEFAULT NULL,
    `window_end` TIMESTAMP NULL DEFAULT NULL,
    `content` TEXT NOT NULL,
    `payload_json` LONGTEXT DEFAULT NULL,
    `source_outcome_ids` LONGTEXT DEFAULT NULL,
    `summary_key` VARCHAR(64) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_summary_key` (`summary_key`),
    KEY `idx_summary_bot_goal` (`bot_guid`, `goal_identity`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Incremental ingestion cursors for the mod-llm-chatter consumer. mod-llm-chatter's
-- own tables are never altered: only this cursor table is owned by this module.
CREATE TABLE IF NOT EXISTS `azeroth_friend_consumer_checkpoints` (
    `consumer` VARCHAR(32) NOT NULL,
    `last_event_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `last_message_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `overlap_seconds` INT UNSIGNED NOT NULL DEFAULT 30,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`consumer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
